image: node:latest 

cache:
  paths:
   - node_modules/

before_script:
  - npm install -g gulp
  - npm install

stages:
  - build_test

build_test:
  stage: build_test
  script:
   echo "Starting gulp build"
   - gulp build
   echo "Starting gulp testing"
   - npm run test

    